/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package git.ipc1.View.users;

import git.ipc1.Models.usuarios.Arrayuser;
import git.ipc1.View.menuPrincipal.MenuPrincipal;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Usersframe extends javax.swing.JFrame {

    private Arrayuser list;

    /**
     * Creates new form Users
     */
    public Usersframe(Arrayuser list) {
        initComponents();
        this.list = list;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonADD = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        LabelName = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonADD.setText("ADD");
        ButtonADD.setPreferredSize(new java.awt.Dimension(50, 30));
        ButtonADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonADDMouseClicked(evt);
            }
        });
        getContentPane().add(ButtonADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 70, 50));

        ButtonExit.setText("EXIT");
        ButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonExitMouseClicked(evt);
            }
        });
        getContentPane().add(ButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 112, -1, 50));

        LabelName.setText("Name");
        getContentPane().add(LabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        getContentPane().add(TextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 164, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonADDMouseClicked
        String tmpname = TextFieldName.getText().trim();
        if (!tmpname.isEmpty()) {
            list.addUsers(tmpname);
            this.jTextArea1.setText(list.toString());
            TextFieldName.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonADDMouseClicked

    private void ButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseClicked
        this.dispose();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonExitMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.jTextArea1.setText(list.toString());        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonADD;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JLabel LabelName;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
