/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package git.ipc1.view.menuprincipal;

import git.ipc1.models.usuarios.Arrayuser;
import git.ipc1.view.damas.DamasFrame;
import git.ipc1.view.hanoi.HanoiForm;
import git.ipc1.view.users.EditUsers;
import git.ipc1.view.users.Usersframe;
import java.awt.Label;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author HP
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Arrayuser usersgame = new Arrayuser();
    private String[] inteto = new String[20];

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
//        ImageIcon pic = new ImageIcon(getClass().getResource("/pictures/fichaNn.jpg"));
//        JLabel did = new JLabel(pic);
//        did.setVisible(true);
//        did.setBounds(100, 100, 100, 100);
//        this.add(did);
    }

    public void rellenarIntento() {
        ComboBoxUser1.removeAllItems();
        ComboBoxUser2.removeAllItems();
        for (int i = 0; i < 20; i++) {
            try {
                if (!usersgame.getTona(i).equals("vacio")) {
                ComboBoxUser1.addItem(usersgame.getTona(i));
                ComboBoxUser2.addItem(usersgame.getTona(i));
                //System.out.println(usersgame.getTona(i));
            }
            } catch (Exception e) {
                //casilla invalida
               // System.out.println("error en rellenar intento");
                break;
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonUsers = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxUser2 = new javax.swing.JComboBox<>();
        ComboBoxUser1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        TextFieldEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonUsers.setText("Users");
        ButtonUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonUsersMouseClicked(evt);
            }
        });
        getContentPane().add(ButtonUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jButton2.setText("Play");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Damas", "Hanoi" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu Principal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        getContentPane().add(ComboBoxUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        getContentPane().add(ComboBoxUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1Player", "2Players" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jButton1.setText("Edit Users");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));
        getContentPane().add(TextFieldEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 80, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String option = (String) this.jComboBox1.getSelectedItem();
        if (option.equals("Hanoi")) {
            jComboBox2.setVisible(false);
            jComboBox2.setSelectedIndex(0);
            ComboBoxUser2.setVisible(false);
        }
        if (option.equals("Damas")) {
            jComboBox2.setVisible(true);
            ComboBoxUser2.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ButtonUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonUsersMouseClicked
      
        new Usersframe(usersgame).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonUsersMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        rellenarIntento();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

        /*
        String option1 = (String) this.ComboBoxUser2.getSelectedItem();
        if (option1.equals("2Players")){
        ComboBoxUser2.setVisible(true);
        }
        if (option1.equals("1Player")){
        ComboBoxUser2.setVisible(false);
        }
        */
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (this.TextFieldEdit.getText().trim().length()==0){
            //System.out.println("error1");
            return;
        }
        int idUpdate;
        try {
            idUpdate = Integer.parseInt(this.TextFieldEdit.getText().trim());

        } catch (Exception e) {
            idUpdate=-1;
                      //  System.out.println("error2");

        }
        if(!Arrayuser.isValid(idUpdate)){
            //id no existe error
             //System.out.println("error3");
            return;
                      
        }
        //existe
        // System.out.println(idUpdate);
         this.TextFieldEdit.setText("");
        new EditUsers(usersgame.getUserEnArray(idUpdate));
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String option = (String) this.jComboBox1.getSelectedItem();
        if (option.equals("Hanoi")) {
            new HanoiForm();
        }
        if (option.equals("Damas")) {
            //            new DamasFrame(1,1);
            new DamasFrame();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*Board t = new Board();
        System.out.println(t);*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonUsers;
    private javax.swing.JComboBox<String> ComboBoxUser1;
    private javax.swing.JComboBox<String> ComboBoxUser2;
    private javax.swing.JTextField TextFieldEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
